require('utkuuci.plugins-setup')
require('utkuuci.core.options')
require('utkuuci.core.keymaps')
require('utkuuci.core.colorscheme')
require('utkuuci.plugins.comment')
require('utkuuci.plugins.nvim-tree')
require('utkuuci.plugins.lualine')
require('utkuuci.plugins.telescope')
require('utkuuci.plugins.nvim-cmp')
require('utkuuci.plugins.lsp.mason')
require('utkuuci.plugins.lsp.lspsaga')
require('utkuuci.plugins.lsp.lspconfig')
require('utkuuci.plugins.autopair')
require('utkuuci.plugins.treesitter')
require('utkuuci.plugins.gitsign')

